### ISSUE TITLE
Spotify Web API 'Authorize web API access' - leads to 'INVALID_CLIENT: Invalid redirect URI'

### ISSUE THREAD

**Issue by aanno** [owntone/owntone-server#1234]
Please try to provide the following:

- version 27.4 (self-compiled from 'master')
- fedora 34
- Compiled with support for ffmpeg, Spotify, LastFM, Chromecast, MPD, Websockets, ALSA, Pulseaudio, Webinterface, Regex.

Steps to reproduce:
1. I logged into my (paid) spotify account at 'Settings -> Online Services' of the web UI.
2. I pressed the 'Authorize web API access' button.
3. This opened the URL `https://accounts.spotify.com/authorize/?client_id=0e684a5422384114a8ae7ac020f01789&response_type=code&redirect_uri=http%3A%2F%2Fowntone.local%3A3689%2Foauth%2Fspotify&scope=playlist-read-private%20playlist-read-collaborative%20user-library-read%20user-read-private&show_dialog=false`
4. 'INVALID_CLIENT: Invalid redirect URI' was shown

I also tried to register a new (spotify) application at https://developer.spotify.com/dashboard/applications and set the Redirect URL to http://owntone.local:3689 . However, I observed that the 'client_id' of the URL is different from the client_id used by owntone. Hence I wonder if there a way to 

1. Enter the client_id to owntone _or_
2. Edit some owntone files to manually set the client_id _and_ client_secret?

PS: 
I used the browser on the host owntone is running on with the following URL for the web UI: http://owntone.local:3689 .

**Comment by ejurgensen** [comment]
To be honest I haven't tested this since the recent renaming of forked-daapd to owntone, so it is possible it just isn't working right now. I will check that. So you could try to go back to the latest release version where the name was forked-daapd and use that. Then you must check that navigating to http://forked-daapd.local:3689/ works, because that is where the redirect goes.

You shouldn't need to register a Spotify application or anything like that, and I wouldn't recommend fiddling with client ID's/secrets.

**Comment by ejurgensen** [comment]
Hi again, actually I just tried, and I see that there was indeed an error from the renaming. Spotify was redirecting to owntone-server.local, not owntone.local. Should be fixed now, worked for me, so please try again (no need to go back to forked-daapd):

**Comment by aanno** [comment]
Yes, the 'Authorize web API access' button now works.

However, I still can't use spotify. Here is want the debug log says when I try to play the album 'Future Days (Remastered)' from 'CAN' (' spotify: Can't play music, not connected and logged in to Spotify'):
```
[2021-05-07 09:33:11] [DEBUG]      web: JSON api request: '/api/queue/items/add?uris=library:album:2105706046942789051&shuffle=false&clear=true&playback=start'
[2021-05-07 09:33:11] [DEBUG]       db: Running query 'BEGIN TRANSACTION;'
[2021-05-07 09:33:11] [DEBUG]       db: Running query 'SELECT value FROM admin a WHERE a.key = 'queue_version';'
[2021-05-07 09:33:11] [DEBUG]       db: Running query 'DELETE FROM queue where id <> 0;'
[2021-05-07 09:33:11] [DEBUG]       db: Running query 'INSERT OR REPLACE INTO admin (key, value) VALUES ('queue_version', '75');'
[2021-05-07 09:33:11] [DEBUG]       db: Running query 'END TRANSACTION;'
[2021-05-07 09:33:11] [DEBUG]      mpd: Asynchronous listener callback called with event type 2.
[2021-05-07 09:33:11] [DEBUG]      mpd: Notify clients waiting for idle results: 2
[2021-05-07 09:33:11] [DEBUG]   player: Status update - status: 2, events: 16, caller: options_generic_bh
[2021-05-07 09:33:11] [DEBUG]      mpd: Asynchronous listener callback called with event type 16.
[2021-05-07 09:33:11] [DEBUG]      mpd: Notify clients waiting for idle results: 16
[2021-05-07 09:33:11] [DEBUG]   player: Player status: stopped
[2021-05-07 09:33:11] [DEBUG]       db: Running query 'BEGIN TRANSACTION;'
[2021-05-07 09:33:11] [DEBUG]       db: Running query 'SELECT value FROM admin a WHERE a.key = 'queue_version';'
[2021-05-07 09:33:11] [DEBUG]       db: Running query 'SELECT COUNT(*) FROM queue;'
[2021-05-07 09:33:11] [DEBUG]       db: Running query 'SELECT COUNT(*) FROM files f WHERE f.disabled = 0 AND (f.songalbumid = 2105706046942789051);'
[2021-05-07 09:33:11] [DEBUG]       db: Starting query 'SELECT f.* FROM files f WHERE f.disabled = 0 AND (f.songalbumid = 2105706046942789051)  ORDER BY f.album_sort, f.disc, f.track ;'
[2021-05-07 09:33:11] [DEBUG]       db: Player queue query returned 1 items
[2021-05-07 09:33:11] [DEBUG]       db: Running query 'INSERT INTO queue (file_id, pos, shuffle_pos, data_kind, media_kind, song_length, path, virtual_path, title, artist, album_artist, album, genre, songalbumid, time_modified, artist_sort, album_sort, album_artist_sort, year, track, disc, artwork_url, queue_version, composer, songartistid, type, bitrate, samplerate, channels) VALUES (76, 0, 0, 2, 1, 183920, 'spotify:track:2C5TxbZmvgs846aq4ZUBRQ', '/spotify:/CAN/Future Days (Remastered)/Moonshake', 'Moonshake', 'CAN', 'CAN', 'Future Days (Remastered)', 'Unknown genre', 2105706046942789051, 1620005733, 'CAN', 'Future Days (Remastered)', 'CAN', 1973, 3, 1, NULL, 76, NULL, 9031324280289689387, 'spotify', 0, 0, 0);'
[2021-05-07 09:33:11] [DEBUG]       db: Added song id 76 (Moonshake) to queue with item id 55
[2021-05-07 09:33:11] [DEBUG]       db: End of query results
[2021-05-07 09:33:11] [DEBUG]       db: Running query 'INSERT OR REPLACE INTO admin (key, value) VALUES ('queue_version', '76');'
[2021-05-07 09:33:11] [DEBUG]       db: Running query 'END TRANSACTION;'
[2021-05-07 09:33:11] [DEBUG]      mpd: Asynchronous listener callback called with event type 2.
[2021-05-07 09:33:11] [DEBUG]      mpd: Notify clients waiting for idle results: 2
[2021-05-07 09:33:11] [DEBUG]       db: Running query 'BEGIN TRANSACTION;'
[2021-05-07 09:33:11] [DEBUG]       db: Starting enum 'SELECT * FROM queue f WHERE pos = 0 ORDER BY pos;'
[2021-05-07 09:33:11] [DEBUG]       db: Running query 'END TRANSACTION;'
[2021-05-07 09:33:11] [DEBUG]   player: Start playback of 'spotify:track:2C5TxbZmvgs846aq4ZUBRQ' (id=76, item-id=55)
[2021-05-07 09:33:11] [DEBUG]       db: Running query 'SELECT f.* FROM files f WHERE f.id = 76;'
[2021-05-07 09:33:11] [DEBUG]   player: Opening track: 'spotify:track:2C5TxbZmvgs846aq4ZUBRQ' (id=55, seek=0)
[2021-05-07 09:33:11] [DEBUG]       db: Running query 'BEGIN TRANSACTION;'
[2021-05-07 09:33:11] [DEBUG]       db: Starting enum 'SELECT * FROM queue f WHERE id = 55 ORDER BY pos;'
[2021-05-07 09:33:11] [DEBUG]       db: Running query 'END TRANSACTION;'
[2021-05-07 09:33:11] [DEBUG]   player: Setting up input item 'spotify:track:2C5TxbZmvgs846aq4ZUBRQ' (item id 55)
[2021-05-07 09:33:11] [DEBUG]  spotify: Playback setup request
[2021-05-07 09:33:11] [DEBUG]  spotify: Setting up for playback
[2021-05-07 09:33:11] [  LOG]  spotify: Can't play music, not connected and logged in to Spotify
[2021-05-07 09:33:11] [DEBUG]       db: Running query 'BEGIN TRANSACTION;'
[2021-05-07 09:33:11] [DEBUG]       db: Starting enum 'SELECT * FROM queue f WHERE id = 55 ORDER BY pos;'
[2021-05-07 09:33:11] [DEBUG]       db: Running query 'END TRANSACTION;'
[2021-05-07 09:33:11] [DEBUG]       db: Running query 'BEGIN TRANSACTION;'
[2021-05-07 09:33:11] [DEBUG]       db: Running query 'SELECT value FROM admin a WHERE a.key = 'queue_version';'
[2021-05-07 09:33:11] [DEBUG]       db: Starting enum 'SELECT * FROM queue f WHERE id = 55 ORDER BY pos;'
[2021-05-07 09:33:11] [DEBUG]       db: Running query 'DELETE FROM queue where id = 55;'
[2021-05-07 09:33:11] [DEBUG]       db: Running query 'UPDATE queue SET pos = pos - 1, queue_version = 77 WHERE pos > 0;'
[2021-05-07 09:33:11] [DEBUG]       db: Running query 'UPDATE queue SET shuffle_pos = shuffle_pos - 1, queue_version = 77 WHERE shuffle_pos > 0;'
[2021-05-07 09:33:11] [DEBUG]       db: Running query 'INSERT OR REPLACE INTO admin (key, value) VALUES ('queue_version', '77');'
[2021-05-07 09:33:11] [DEBUG]       db: Running query 'END TRANSACTION;'
[2021-05-07 09:33:11] [DEBUG]      mpd: Asynchronous listener callback called with event type 2.
[2021-05-07 09:33:11] [DEBUG]   player: Opening track: 'spotify:track:2C5TxbZmvgs846aq4ZUBRQ' (id=55, seek=0)
[2021-05-07 09:33:11] [DEBUG]      mpd: Notify clients waiting for idle results: 2
[2021-05-07 09:33:11] [DEBUG]       db: Running query 'BEGIN TRANSACTION;'
[2021-05-07 09:33:11] [DEBUG]       db: Starting enum 'SELECT * FROM queue f WHERE id = 55 ORDER BY pos;'
[2021-05-07 09:33:11] [DEBUG]       db: End of queue enum results
[2021-05-07 09:33:11] [DEBUG]       db: Running query 'END TRANSACTION;'
[2021-05-07 09:33:11] [  LOG]   player: Input start was called with an item id that has disappeared (id=55)
[2021-05-07 09:33:11] [DEBUG]       db: Running query 'BEGIN TRANSACTION;'
[2021-05-07 09:33:11] [DEBUG]       db: Starting enum 'SELECT * FROM queue f WHERE id = 55 ORDER BY pos;'
[2021-05-07 09:33:11] [DEBUG]       db: End of queue enum results
[2021-05-07 09:33:11] [DEBUG]       db: Running query 'END TRANSACTION;'
[2021-05-07 09:33:11] [  LOG]   player: Error fetching next item from queue (item-id=55, repeat=1)
[2021-05-07 09:33:11] [DEBUG]       db: Running query 'BEGIN TRANSACTION;'
[2021-05-07 09:33:11] [DEBUG]       db: Running query 'SELECT value FROM admin a WHERE a.key = 'queue_version';'
[2021-05-07 09:33:11] [DEBUG]       db: Starting enum 'SELECT * FROM queue f WHERE id = 55 ORDER BY pos;'
[2021-05-07 09:33:11] [DEBUG]       db: End of queue enum results
[2021-05-07 09:33:11] [DEBUG]       db: Running query 'END TRANSACTION;'
```

**Comment by ejurgensen** [comment]
Are you logged in via libspotify? (the web API is not enough for playback, due to Spotify, unfortunately)

Check Settings > Online sources in the web interface.

**Comment by aanno** [comment]
![owntone-spotify](https://user-images.githubusercontent.com/824933/117424434-102c0000-af22-11eb-852d-6ad6e6491680.jpg)

**Comment by ejurgensen** [comment]
Ok, then I'm guessing there is something stopping libspotify from working. Could be permissions the directories it uses (see the bottom of owntone's config file).

**Comment by aanno** [comment]
```bash
$ ls -Rl /var/cache/owntone
/var/cache/owntone:
insgesamt 9440
-rw-r--r--. 1 tpasch tpasch 9359360  7. Mai 10:42 cache.db
drwxr-xr-x. 3 tpasch tpasch      57  7. Mai 11:37 libspotify
-rw-r--r--. 1 tpasch tpasch  307200  7. Mai 11:37 songs3.db

/var/cache/owntone/libspotify:
insgesamt 8
-rw-rw-r--. 1 tpasch tpasch 396  7. Mai 11:37 settings
-rw-rw-r--. 1 tpasch tpasch  38  6. Mai 19:28 user-cache.bnk
drwxr-xr-x. 3 tpasch tpasch  29  6. Mai 19:25 Users

/var/cache/owntone/libspotify/Users:
insgesamt 0
drwxr-xr-x. 2 tpasch tpasch 148  7. Mai 12:12 aannoaanno-user

/var/cache/owntone/libspotify/Users/aannoaanno-user:
insgesamt 12
-rw-rw-r--. 1 tpasch tpasch 174  7. Mai 12:12 offline2
-rw-rw-r--. 1 tpasch tpasch 222  6. Mai 19:28 playlist-0000000000000000000000000000000005.bnk
-rw-rw-r--. 1 tpasch tpasch 456  7. Mai 10:47 playlist.bnk
-rw-rw-r--. 1 tpasch tpasch   0  7. Mai 10:47 social_manager.bnk
-rw-rw-r--. 1 tpasch tpasch   0  7. Mai 12:12 social_stream.bnk

$ tree -al /var/cache/owntone
/var/cache/owntone
├── cache.db
├── libspotify
│   ├── settings
│   ├── user-cache.bnk
│   └── Users
│       └── aannoaanno-user
│           ├── offline2
│           ├── playlist-0000000000000000000000000000000005.bnk
│           ├── playlist.bnk
│           ├── social_manager.bnk
│           └── social_stream.bnk
└── songs3.db

3 directories, 9 files
```

**Comment by aanno** [comment]
Would it help to try e.g. [spotify](https://github.com/Spotifyd/spotifyd) and see if it works? Fedora is a complex beast with SELinux and all the modern bells and whistles...

**Comment by ejurgensen** [comment]
I have another suggestion for you which might be more simple - I will get back to you later today :-)

**Comment by ejurgensen** [comment]
So what I propose is that you pull from the repo again, and then checkout the branch called "spotifyc1" and build + run. This is an experimental branch, where Spotify playback does not require libspotify. I hope you don't mind being a guinea pig.

Setup-wise, the only thing you need to do is go to the Spotify settings again and login to "libspotify" (it is not really libspotify, the UI just hasn't been updated yet). You shouldn't need to login into the web API again.

If you run into issues with the new branch please comment [on this pull request](https://github.com/owntone/owntone-server/pull/1230).

**Comment by aanno** [comment]
Spotify works like a charm with your `spotifyc1` branch. Great work! Thank you very much!

**Comment by alesrosina** [comment]
Sorry for commenting on already closed issue, but I do get this error on latest version, if i change web interface port from 3689 to 80. Since this is the only web service I run on raspi, it's easier to access when it's running on port 80.

**Comment by ejurgensen** [comment]
You need to use 3689 when authorizing. It is one-off, so you can switch to 80 after. The reason is that Spotify redirects back to an address that is set to owntone.local:3689. It is an app setting at Spotify that you cannot change.

**Comment by alesrosina** [comment]
Makes sense. If you could just add this sentence in docs, that would be super helpful, since i guess i'm not the only one with this case :)

And thanks for fast response!

**Comment by ejurgensen** [comment]
The docs already have it, I would say: "You must also make sure that your browser can reach OwnTone's web interface via the address http://owntone.local:3689. Try it right now! That is where Spotify's OAuth page will redirect your browser with the token that OwnTone needs, so it must work"

**Comment by alesrosina** [comment]
Yes, now that I know it's obvious - but at the beginning, this was not so obvious. Anyway, since there are no other issues similar to this, I guess it's only me who didn't get it at first ;)
