### ISSUE TITLE
Artwork images not displayed, 'Error occurred while encoding: Input/output error'

### ISSUE THREAD

**Issue by SamuelCook** [owntone/owntone-server#1298]
I upgraded from forked-daapd 27.4 to owntone 28.1 which overall went smoothly, but am now seeing errors when attempting to display album artwork.

Unfortunately I also upgraded several other components on my media server Rasperry Pi 4, including ffmpeg (to 4.3.2), so it's difficult to track down an individual culprit. Could you please take a look at the attached log file and let me know what I can do to investigate this further?

The media library hasn't changed since the upgrade, and the artwork loads just fine in other music players for the file mentioned in the log.

[owntone_artwork_errors.log](https://github.com/owntone/owntone-server/files/7033549/owntone_artwork_errors.log)

**Comment by ejurgensen** [comment]
Thanks for the notification, and also for a good log extract. It does indeed look like the issue is related to ffmpeg. These errors are from ffmpeg:

```
[2021-08-19 15:04:43] [ WARN]    xcode: av_interleaved_write_frame() failed: Input/output error
[2021-08-19 15:04:43] [  LOG]    xcode: Error occurred while encoding: Input/output error
```

I will see if I can reproduce with ffmpeg 4.3.2. Just in case I can't, can you the send/share the file with the artwork? My address is espenjurgensen@gmail.com.

**Comment by ejurgensen** [comment]
I couldn't reproduce this with Ubuntu 21.04 (which has ffmpeg 4.3.2), but I have an RPi4 on the way, so will try again when that arrives.

**Comment by ejurgensen** [comment]
I've now published a version for Bullseye, see [the instructions here](https://www.raspberrypi.org/forums/viewtopic.php?t=49928). I had to do some updates to how the repository is made, so took a while.

**Comment by SamuelCook** [comment]
The instructions worked perfectly, thank you! Best of all: artwork is back. I still see the following in the logs, but it seems harmless:

```
[ WARN]   ffmpeg: stream 0, timescale not set
```

Thank you so much for diagnosing and resolving this!
