### ISSUE TITLE
[help request] Radio Stream naming and artwork

### ISSUE THREAD

**Issue by cdlenfert** [owntone/owntone-server#1829]
Hi, I've been trying to update a radio stream using the new URL. The options for streaming are all available under "Alternate streaming options" [on this site](https://coloradosound.org/listen/). I first tried to go the route of using the M3U8 (i.e. HLS) stream because it worked well in VLC to show the track and artist info. However I gave that up because Owntone never seemed to be able to pick up this metadata. 

I found that the MP3 Stream had this same metadata, so I went with that instead and it's working well. http://ais-sa1.streamon.fm/7891_96k.mp3

The only remaining issues I have is that I cannot seem to name the Radio Station in Owntone. It only wants to use the "7891_96k.mp3" part of the stream URL. And I can't get my manual artwork to appear.

Here are my files:
```
-rw-r--r-- 1 dietpi dietpi   78 Dec 28 09:20 'The Colorado Sound.m3u'
-rwxrw-rw- 1 dietpi dietpi  57K May 20  2020 'The Colorado Sound.png'
```
and the contents of the m3u:
```
root@rockpi:/mnt/pogo1/ext-misc/owntone/ot-playlists# cat The\ Colorado\ Sound.m3u 
#EXTM3U
#EXTINF:-1,The Colorado Sound
http://ais-sa1.streamon.fm/7891_96k.mp3
```
I removed and recreated the m3u file, performed a full library and forced metadata rescan, but it's still like this.
![image](https://github.com/user-attachments/assets/2c35d944-1370-47d8-a35c-9ae5fff8e284)
![image](https://github.com/user-attachments/assets/d1e36a71-5269-4850-b12f-6d716a5f9c56)

Thanks for any input.

**Comment by cdlenfert** [comment]
Oh, and here is how it appears in the API
```
{
"id": 496,
"name": "The Colorado Sound",
"path": "[/mnt/pogo1/ext-misc/owntone/ot-playlists/The Colorado Sound.m3u](http://owntone.local:3689/mnt/pogo1/ext-misc/owntone/ot-playlists/The%20Colorado%20Sound.m3u)",
"parent_id": "0",
"type": "plain",
"smart_playlist": false,
"random": false,
"folder": false,
"item_count": 1,
"stream_count": 1,
"uri": "library:playlist:496"
},
```

**Comment by hacketiwack** [comment]
That would be great if this could be improved indeed.
I have a lot of radio stations in OwnTone, but how they are displayed is not optimal.

**Comment by ejurgensen** [comment]
Hi @cdlenfert, you can set the title via m3u as described [here](https://owntone.github.io/owntone-server/advanced/radio-streams/). So for instance: `#EXTINF:-1,The Colorado Sound - The Colorado Sound`

As you can see, there's also some info about dynamic radio station artwork, but perhaps you just want static artwork? I think that should be possible too, but let me know what you tried.

**Comment by LordMyschkin** [comment]
this does not work for me:
the playlist entry: 
```
#EXTINF:-1, - Cafe del Mar
https://streams.radio.co/se1a320b47/listen
```
(There seems to be a problem in displaying characters with accents, wich I tried to circumvent)
is displayed as 
<img width="259" alt="image" src="https://github.com/user-attachments/assets/0ef6d2ff-234b-44c8-9413-85d2c2a3f27c" />

**Comment by ejurgensen** [comment]
I can't reproduce any problem, but maybe you don't have `m3u_overrides` enabled? If you don't set that OwnTone will use the metadata from the radio station.

**Comment by LordMyschkin** [comment]
I was in indeed not aware of this switch, now - even with accents on "Café del mar" and "Ö3" - everything works as It should
<img width="342" alt="image" src="https://github.com/user-attachments/assets/18de0972-7a69-4161-89b0-216be083b196" />
Thank you so much!

**Comment by cdlenfert** [comment]
I also didn't know about the `m3u_overrides` setting in the config file, but it turns out, I didn't have to enable that to get the name of the radio station updated in OwnTone. I was just not using the correct format for the name in the M3U file.

By having this content:
```
#EXTM3U
#EXTINF:-1,The Colorado Sound
http://ais-sa1.streamon.fm/7891_96k.mp3
```
This only populates the Artist Name with "The Colorado Sound". I was confused when I saw [examples](https://owntone.github.io/owntone-server/advanced/radio-streams/#1-set-stream-nametitle-via-the-m3u-file) like `#EXTINF:-1, - The Colorado Sound` and I didn't know what the dash was for. Everything after the dash is the "Track Title", and that Track Title is what OwnTone shows in the Radio section list.
![image](https://github.com/user-attachments/assets/8864aaf8-b70d-49c3-8761-d0307926865e)

So after updating my M3U file contents to the following, things are better now:
```
#EXTM3U
#EXTINF:-1, - The Colorado Sound
http://ais-sa1.streamon.fm/7891_96k.mp3
```
![image](https://github.com/user-attachments/assets/ce81e297-4373-44f4-9b9a-2221d39777e4)

I would love to get artwork for this station, but reading through the [Radio Streams guide](https://owntone.github.io/owntone-server/advanced/radio-streams/#radio-streams), I'm not sure how to manage this particular stream.

Here's what I get with `ffprobe` for the MP3 stream:
```
Input #0, mp3, from 'http://ais-sa1.streamon.fm/7891_96k.mp3':
  Metadata:
    icy-br          : 100
    icy-genre       : various
    icy-name        : 
    icy-url         : 
    icy-description : Unspecified description
    icy-pub         : 0
    StreamTitle     : Ray LaMontagne - Step Into Your Power
    StreamUrl       : http://metadata.cdnstream1.com/?Album=Long+Way+Home&category=music&GROUP=%7B%22allow_inserting%22%3A+false%2C+%22name%22%3A+%22Music%22%2C+%22display_in_player%22%3A+true%2C+%22allow_replacing%22%3A+false%2C+%22allow_replaying%22%3A+false%2C+%22allow_shar
  Duration: N/A, start: 0.000000, bitrate: 99 kb/s
  Stream #0:0: Audio: mp3, 32000 Hz, stereo, fltp, 99 kb/s
  ```
What's The artist and are being scraped automatically by OwnTone. I can see that there is album info in the `StreamUrl` but the address gets cut off and I can't examine any JSON that might be present.

OwnTone's logs are showing an attempt to get the artwork, but it fails:
```
[2024-12-31 09:49:32] [  LOG]     http: Request to http://metadata.cdnstream1.com/?Album=Blow+Your+Cool&category=music&GROUP=%7B%22allow_inserting%22%3A+false%2C+%22name%22%3A+%22Music%22%2C+%22display_in_player%22%3A+true%2C+%22allow_replacing%22%3A+false%2C+%22allow_replaying%22%3A+false%2C+%22allow_sharing%22%3A+false%2C+%22allow_replacement_skipping%22%3A+false%7D&RADIO_STATION=KJAC&ARTIST=Hoodoo+Gurus&EVENT_ID=1735663715.724494&TITLE=What%27s+My+Scene&ITUNES_SONG_ID=298090008&WWW_ALBUM_ART=https%3A%2F%2Fis1-ssl.mzstatic.com%2Fimage%2Fthumb%2FMusic%2F11%2Fcc%2F21%2Fmzi.nepwiuir.jpg%2F170x170bb.jpg&commercial_information=https://is1-ssl.mzstatic.com/image/thumb/Music/11/cc/21/mzi.nepwiuir.jpg/170x170bb.jpg failed: Couldn't resolve host name
[2024-12-31 09:49:32] [  LOG]  artwork: Request to 'http://metadata.cdnstream1.com/?Album=Blow+Your+Cool&category=music&GROUP=%7B%22allow_inserting%22%3A+false%2C+%22name%22%3A+%22Music%22%2C+%22display_in_player%22%3A+true%2C+%22allow_replacing%22%3A+false%2C+%22allow_replaying%22%3A+false%2C+%22allow_sharing%22%3A+false%2C+%22allow_replacement_skipping%22%3A+false%7D&RADIO_STATION=KJAC&ARTIST=Hoodoo+Gurus&EVENT_ID=1735663715.724494&TITLE=What%27s+My+Scene&ITUNES_SONG_ID=298090008&WWW_ALBUM_ART=https%3A%2F%2Fis1-ssl.mzstatic.com%2Fimage%2Fthumb%2FMusic%2F11%2Fcc%2F21%2Fmzi.nepwiuir.jpg%2F170x170bb.jpg&commercial_information=https://is1-ssl.mzstatic.com/image/thumb/Music/11/cc/21/mzi.nepwiuir.jpg/170x170bb.jpg' failed with return value -1
[2024-12-31 09:49:32] [  LOG]  artwork: Source 'stream' returned an error for 'The Colorado Sound'
```

There is a more full URL in there, and at the end I see a parameter `commercial_information=` with a URL that hits an actual artwork image. https://is1-ssl.mzstatic.com/image/thumb/Music/11/cc/21/mzi.nepwiuir.jpg/170x170bb.jpg. I can also see the Album title `Album=Blow+Your+Cool`. 

What would be great is to ultimately have the station named "The Colorado Sound" in the Radio list in OwnTone, and when playing, show the track, artist, title, and artwork of the currently playing song.

I'm guessing I need to have a custom script that populates these values from the StreamUrl address to OwnTone via the JSON API. That's a bit out of my wheelhouse. One question that comes to mind is how do I do this so the script only does this for a specific radio station? And do I use a cronjob to have it run every few seconds? Is there a way to piggyback off of what OwnTone is already doing to check the metadata when a track changes?

The above is a best case scenario, so no worries if I don't get it fully sorted out, I'm in much better shape now than I was. Thanks everyone!

**Comment by ejurgensen** [comment]
Yes, I agree writing a script is going to be cumbersome. I have tried to make a modification to the streamurl handler in OwnTone so that it can also extract url's from within the streamurl. The modification is in the streamurl_direct branch. It's completely untested, but the idea is that could set a keyword that OwnTone will look for in the url. So tell OwnTone the keyword like this:

`curl -X PUT "http://localhost:3689/api/settings/misc/streamurl_keywords_artwork_url" --data "{\"name\":\"streamurl_keywords_artwork_url\",\"value\":\"commercial_information\"}`

Alternatively, did you try enabling any of the online artwork sources? It's a setting in the web UI. I suppose that would be the easiest, though it might not return as precise artwork as the radio station itself. However, I notice the image from the radio station is quite low resolution, so an online artwork source will be better in that regard.

**Comment by cdlenfert** [comment]
Thanks! I've done some initial testing, but before I summarize the results a bit about the artwork fetching services.

I do have Spotify artwork fetching enabled. I'm curious if that fetching would work on the radio stream if I were able to capture and parse the Album info from the `StreamUrl` (i.e. `http://metadata.cdnstream1.com/?Album=Blow+Your+Cool`). The artwork from the actual stream is indeed very low res, so this would be a better option in my opinion. 

In the new `streamurl_direct` branch, I've done the following:

Set the `streamurl_keywords_artwork_url` value to "commercial_information" as is present in the `StreamUrl` value `... &commercial_information=https://is1-ssl.mzstatic.com/image/thumb/Music/11/cc/21/mzi.nepwiuir.jpg/170x170bb.jpg`
```
root@rockpi:/home/dietpi/owntone-server# curl -X PUT "http://localhost:3689/api/settings/misc/streamurl_keywords_artwork_url"      --data "{\"name\":\"streamurl_keywords_artwork_url\",\"value\":\"commercial_information\"}"
```
Confirm that the keyword is being set.
```
root@rockpi:/home/dietpi/owntone-server# curl "http://localhost:3689/api/settings/misc"
{ "name": "misc", "options": [ { "name": "streamurl_keywords_artwork_url", "type": 2, "value": "commercial_information" }, { "name": "streamurl_keywords_length", "type": 2 } ] }
```

No artwork appears in the web UI. 

Restart OwnTone with debug logging enabled and here's everything relevant from the log that I can find:
```
[2025-01-01 10:07:48] [DEBUG]       db: Running query 'SELECT value FROM admin a WHERE a.key = 'use_artwork_source_coverartarchive';'
[2025-01-01 10:07:48] [DEBUG]       db: Running query 'SELECT value FROM admin a WHERE a.key = 'streamurl_keywords_artwork_url';'
[2025-01-01 10:07:48] [DEBUG]       db: Running query 'SELECT value FROM admin a WHERE a.key = 'streamurl_keywords_length';'
[2025-01-01 10:07:48] [DEBUG]       db: No results
```
```
[2025-01-01 10:09:17] [DEBUG]       db: Running query 'SELECT value FROM admin a WHERE a.key = 'streamurl_keywords_artwork_url';'
```
Tried setting the value again:
```
[2025-01-01 10:17:20] [DEBUG]      web: JSON API request '/api/settings/misc/streamurl_keywords_artwork_url' in worker thread 252547
[2025-01-01 10:17:20] [DEBUG]       db: Running query 'INSERT OR REPLACE INTO admin (key, value) VALUES ('streamurl_keywords_artwork_url', 'commercial_information');'
[2025-01-01 10:17:20] [ INFO]      web: Setting option 'misc.streamurl_keywords_artwork_url' changed to '{ "name": "streamurl_keywords_artwork_url", "value": "commercial_information" }'
```
If I can get more helpful information in some way please let me know.

**Comment by ejurgensen** [comment]
Now I tried testing myself. The problem is that the StreamUrl ends in "jpg", so OwnTone thinks it's a regular artwork link that will work. That means the special keyword search for "commercial_information" doesn't kick in. I tried overriding this check of the link ending, and using "WWW_ALBUM_ART" as keyword I got album art to work. However, this override will break handling of StreamUrl's with normal artwork links, so it won't work as anything but a hack. And I'm not sure what an alternate approach could be.

**Comment by cdlenfert** [comment]
That makes sense to me. Instead of having it be a setting that overrides the artwork that OwnTone is automatically trying to fetch (since the StreamUrl ends in .jpg), I wonder if it could be done with a script and cron job. Or if there's some way to get the Album value (Album=Blow+Your+Cool) included in OwnTone and have the Spotify album art pulled instead. I realize that might still not work because OwnTone thinks it should be getting a valid album art URL from the StreamUrl address. But OwnTone does seem to know that it's not getting valid artwork via the default method according to the log output:
```
[2025-01-01 13:41:48] [  LOG]     http: Request to http://metadata.cdnstream1.com/?Album=Nice+and+Warm&category=music&GROUP=%7B%22allow_inserting%22%3A+false%2C+%22name%22%3A+%22Music%22%2C+%22display_in_player%22%3A+true%2C+%22allow_replacing%22%3A+false%2C+%22allow_replaying%22%3A+false%2C+%22allow_sharing%22%3A+false%2C+%22allow_replacement_skipping%22%3A+false%7D&RADIO_STATION=KJAC&ARTIST=Tab+Benoit&EVENT_ID=1735764017.990537&TITLE=Nice+and+Warm&ITUNES_SONG_ID=712123871&WWW_ALBUM_ART=https%3A%2F%2Fis1-ssl.mzstatic.com%2Fimage%2Fthumb%2FMusic4%2Fv4%2F10%2F13%2F15%2F10131575-d119-704d-5938-25be102df4cc%2F00015707954259.jpg%2F170x170bb.jpg&commercial_information=https://is1-ssl.mzstatic.com/image/thumb/Music4/v4/10/13/15/10131575-d119-704d-5938-25be102df4cc/00015707954259.jpg/170x170bb.jpg failed: Couldn't resolve host name
[2025-01-01 13:41:48] [  LOG]  artwork: Request to 'http://metadata.cdnstream1.com/?Album=Nice+and+Warm&category=music&GROUP=%7B%22allow_inserting%22%3A+false%2C+%22name%22%3A+%22Music%22%2C+%22display_in_player%22%3A+true%2C+%22allow_replacing%22%3A+false%2C+%22allow_replaying%22%3A+false%2C+%22allow_sharing%22%3A+false%2C+%22allow_replacement_skipping%22%3A+false%7D&RADIO_STATION=KJAC&ARTIST=Tab+Benoit&EVENT_ID=1735764017.990537&TITLE=Nice+and+Warm&ITUNES_SONG_ID=712123871&WWW_ALBUM_ART=https%3A%2F%2Fis1-ssl.mzstatic.com%2Fimage%2Fthumb%2FMusic4%2Fv4%2F10%2F13%2F15%2F10131575-d119-704d-5938-25be102df4cc%2F00015707954259.jpg%2F170x170bb.jpg&commercial_information=https://is1-ssl.mzstatic.com/image/thumb/Music4/v4/10/13/15/10131575-d119-704d-5938-25be102df4cc/00015707954259.jpg/170x170bb.jpg' failed with return value -1
[2025-01-01 13:41:48] [  LOG]  artwork: Source 'stream' returned an error for 'The Colorado Sound'
```
Maybe it can try to process an alternative value if the default attempt fails?

**Comment by ejurgensen** [comment]
> Or if there's some way to get the Album value (Album=Blow+Your+Cool) included in OwnTone and have the Spotify album art pulled instead

I'm not sure what you mean by this? If you enable Spotify as an online artwork source then OwnTone will query Spotify for album artwork using the info from StreamTitle (artist + title). It's a while ago I made that, so maybe it's not working any more?

I tried with Discogs, and it did work with some the tracks being played. I'll see if I can try with Spotify later.

**Comment by cdlenfert** [comment]
I won't pretend to know exactly how this works, but I would expect that album information is necessary in order to get album artwork. Using Spotify as the online artwork source (as I have it configured) works fine as long as there is valid album metadata. But my radio stream doesn't have valid album data, and even if it did, it's unclear to me if the StreamUrl value would have the priority, or if album details were available, if the Spotify artwork source would be used instead. I expect the StreamUrl would be the priority.

I wonder if Discogs was finding some artwork because the name of the track was the same as the name of the album, and it was the same as having valid Artist + Album info.

Here is another stream I listen to, and it has a static artwork in the metadata that never changes (and looks pretty bad). The StreamTitle value is [Artist] - [Track], and there is no album info to be found. In this case, I don't think there's any way to get album artwork to show up in OwnTone, even if we had valid album info somewhere in the stream metadata.
```
Input #0, aac, from 'http://ice4.somafm.com/indiepop-128-aac':
  Metadata:
    icy-br          : 128
    icy-genre       : College Indie
    icy-name        : Indie Pop Rocks! [SomaFM]
    icy-notice1     : <BR>This stream requires <a href="http://www.winamp.com/">Winamp</a><BR>
    icy-notice2     : SHOUTcast Distributed Network Audio Server/Linux v1.9.5<BR>
    icy-pub         : 0
    icy-url         : http://somafm.com
    StreamTitle     : Beach House - Chariot
    StreamUrl       : https://somafm.com/logos/512/indiepop512.png
  Duration: N/A, bitrate: 127 kb/s
  Stream #0:0: Audio: aac (LC), 44100 Hz, stereo, fltp, 127 kb/s
```

**Comment by ejurgensen** [comment]
When OwnTone queries Spotify it just uses artist and title, it doesn't need the album. Here's a query example with a track playing from Colorado Sound:
`https://api.spotify.com/v1/search?type=track&limit=1&q=artist%3ACrosby%2C%20Stills%20%26%20Nash%20track%3ADark%20Star`

Spotify then returns albums with tracks that match, and OwnTone picks artwork from one of these.

However, I notice there is a problem that sometimes OwnTone makes this search instead:
`https://api.spotify.com/v1/search?type=track&limit=1&q=artist%3ACrosby%2C%20Stills%20%26%20Nash%20track%3AThe%20Colorado%20Sound`

Since the track title is incorrect no artwork is found, of course. I think this incorrect search comes from OwnTone swapping radio station name with title for presentation reasons. I'm not sure why it's not always happening, though.

So that's a bug. I also see that OwnTone is attempting searches when artist is "Unknown artist", I also have to do something about that.

**Comment by cdlenfert** [comment]
Ah, that is clever and makes more sense now. 

In the 2 radio streams I shared, both have a StreamUrl value. The Colorado Sound stream (http://ais-sa1.streamon.fm/7891_96k.mp3) has a value that ends in .jpg but is not a valid path to the artwork. The Indie Pop Rocks! stream (http://ice4.somafm.com/indiepop-128-aac) has a value that is valid and points to a PNG that's static. If both of these StreamUrl values could be ignored, then OwnTone (with a possible bug fix)could get artwork from the Spotify API because both `StreamTitle` values include Artist - Track information.

**Comment by ejurgensen** [comment]
I've added some changes to the `streamurl_direct` branch that fix getting artwork from e.g. Spotify for cases like "The Colorado Sound". I also lowered the log severity of the failed calls to the StreamUrl, so that the log isn't filled with those on normal LOG level.

While testing it seems that the station sometimes (during breaks, I think) sets the title as "The Colorado Sound", so that's why OwnTone was searching for it. That will still be the case, but the changes should mean that the search doesn't enter failed state when that search doesn't return anything.

With regard to the placement of the radio station name as title, then that's a case of "works as designed" :-)

**Comment by ejurgensen** [comment]
@barolo I've now also added a setting to the branch that will make OwnTone ignore the StreamUrl from the radio station, like you suggest. Currently, you can only set it via the JSON api, but perhaps @hacketiwack can help add a switch to the web UI settings.

`curl -X PUT "http://localhost:3689/api/settings/misc/streamurl_ignore" --data "{\"name\":\"streamurl_ignore\",\"value\":true}"`

Please confirm that it works.

**Comment by hacketiwack** [comment]
@ejurgensen if I understand correctly, this would be an option in the artwork settings that would not be permanently stored. Correct?

**Comment by ejurgensen** [comment]
Settings are permanently stored in the database (e.g. if you enable "Discogs" as online artwork source, the setting is stored in the database).

I'm not sure what a good caption for this setting might be, perhaps "Ignore artwork served by radio stations (via StreamUrl)".

**Comment by hacketiwack** [comment]
What about the other settings related to streaming:
- streamurl_keywords_artwork_url
- streamurl_keywords_length

Also, instead of having these settings in a category named "Misc", shouldn't we have a better name, like "Streaming"?

**Comment by hacketiwack** [comment]
I created a page for these settings. I'm not a great fan of pages named "Misc", "Miscellaneous", "Common", etc.
The naming should be clearer. Also the naming of these settings is obscure to me. I don't understand how they work.

**Comment by cdlenfert** [comment]
In my experience most radio streams will give you artist and track info, and as @barolo mentioned, if they do give you artwork it's pretty low quality or static for the entire station (like on SOMA). 

Now that I understand how the album is determined using artist + track info for the Spotify artwork query, I doubt I would ever use the `streamurl_keywords_artwork_url` feature, and would always lean toward just disabling the `StreamUrl` artwork.

Here's how that is working out for me and it's pretty awesome.
![IMG_6044 Large](https://github.com/user-attachments/assets/a2c5ed18-5971-497e-975d-5e5fc4beeba7)
![IMG_6046 Large](https://github.com/user-attachments/assets/2bf66083-5875-40c5-b9ba-b9a97f03bdff)

@hacketiwack If the idea it to not include the custom parameter for an artwork value in the `StreamUrl` which @ejurgensen initially implemented, and instead to only allow for the `StreamUrl` to be ignored via a toggle, then I think it could go under the "Artwork" setting since it's artwork specific. Something like this...
<img width="780" alt="image" src="https://github.com/user-attachments/assets/8e813c12-fe15-4973-8380-f59b6dea4231" />

**Comment by hacketiwack** [comment]
@cdlenfert I forgot to generate the new web UI.

**Comment by ejurgensen** [comment]
> I'm not a great fan of pages named "Misc", "Miscellaneous", "Common", etc.

@hacketiwack I agree, but I just meant adding a switch for "streamurl_ignore" under "Artwork", like @cdlenfert illustrated above. The "streamurl_keywords_artwork_url" and "streamurl_keywords_length" are very specialized and have a narrow audience, so I don't think it's terribly important that they are available via the UI. You also won't be changing those very often, while the switch for streamurl_ignore might make sense to switch on and off depending on radio station.

**Comment by cdlenfert** [comment]
I've tested the latest updates and it's working well. The toggle in the new "Miscellaneous" tab for "Ignore album artwork served by radio stations" works as intended. I still think this toggle would be better placed in the "Artwork" tab.

![image](https://github.com/user-attachments/assets/a38d917b-0309-4888-bc58-fdf31f58fee0)

Thanks @ejurgensen and @hacketiwack for making this possible. It really enhances the streaming radio experience nicely.

**Comment by ejurgensen** [comment]
@hacketiwack I have moved this setting and the other one you suggested to the artwork category with the above commit. Only in the C source, hope you can update the web UI source. Moving show_cover_artwork_in_album_lists is in principle a breaking API change, but I guess it's unlikely anyone is actually using that in an API integration, so I think it will be ok.

**Comment by hacketiwack** [comment]
Thanks @ejurgensen I will change the UI soon.

**Comment by hacketiwack** [comment]
Done with the latest [commit](https://github.com/owntone/owntone-server/commit/3dd840d958943bf1f01b7bac9acfe24cb0d971b2)

**Comment by cdlenfert** [comment]
Thanks @hacketiwack. I tested this updated interface. I already had the "ignore artwork provided by radio streams" setting disabled via the command provided by @ejurgensen:

```
curl -X PUT "http://localhost:3689/api/settings/misc/streamurl_ignore" --data "{\"name\":\"streamurl_ignore\",\"value\":true}"
```

I still get artwork from Spotify etc. But my setting is not recognized by the web interface, and I'm unable to toggle the setting when I click on the toggle. It remains greyed out when I click on it.
![image](https://github.com/user-attachments/assets/1dbd7377-ce9b-4b08-99dc-2c02e61617cc)

**Comment by hacketiwack** [comment]
@cdlenfert indeed, there was a small mistake. It is now corrected.

**Comment by cdlenfert** [comment]
Thanks @hacketiwack. Working great for me now.

**Comment by ejurgensen** [comment]
Thanks everyone, merged now with PR #1836

**Comment by ejurgensen** [comment]
@cdlenfert yes I recall that there is some difficulty with supporting non-library items with the artwork module, maybe because all non-library items share the same dummy file id ID internally in OwnTone. I also recall that it's not an easy fix (without becoming ugly).

**Comment by univok** [comment]
Hi, I am trying to override the icy-name of the online radio stream **Fusion 101** at 

[Fusion 101](http://quincy.torontocast.com:2040/stream )

ffprobe gives something like this:
```
    icy-br          : 192
    icy-name        : Online Radio
    icy-pub         : 1
    StreamTitle     : Steve Weingart & Renee Jones - Twenty Twelve - Observatory
```
where `icy-name` is always fixed to `Online Radio`. I want to use the more meaningful name `Fusion 101`, but though I set
`m3u_overrides = true` in the owntone.conf and provided an m3u like
```
#EXTM3U
#EXTINF:-1, - Fusion 101
http://quincy.torontocast.com:2040/stream
```
the name displayed in e.g. **iTunes Remote** sticks to `Online Radio`. I restarted owntone and did a new library scan as well with no effect.

What I am doing wrong?

**Comment by ejurgensen** [comment]
With m3u_overriades set to true and your m3u, Fusion 101 displayed fine when I tried just now. So not sure what the issue could be.

Maybe you could also contact the streamer and suggest they put their a proper name in the ICY metadata.

**Comment by univok** [comment]
Meanwhile I found out that this was a caching problem of the iTunes Remote app. I had to end and restart the app on my iPhone as well, after that everything was fine. Thank you for checking and for this great app!
